### ISSUE TITLE
Displaying 0.

### ISSUE THREAD

**Issue by kiaorapeter** [dryoo/numberof#3]
As is discussed in this forum post; https://forum.dokuwiki.org/post/66825;nocount

I wanted to put in a sentence which read 
_This section has {{NUMBEROFPAGES>:this_section}} pages_

If there were six pages then it would read
_This section has 6 pages_ - this is perfect.
If there were no pages then it would read
_This section has pages_ 

turnermm suggested replacing 

```
case "PAGES":
               search($list,$conf['datadir'].$matches[1],array($this,'_search_count'),array('all'=>false),'');
                $data = $list['file_count'];
                break;
               
 case "MEDIAS":
                search($list,$conf['mediadir'].$matches[1],array($this,'_search_count'),array('all'=>true));
                $data    = $list['file_count'];
                break;
```

with 

```
 case "PAGES":
               search($list,$conf['datadir'].$matches[1],array($this,'_search_count'),array('all'=>false),'');
                $data = $list['file_count'] ? $list['file_count'] : '0';
                break;
               
case "MEDIAS":
                search($list,$conf['mediadir'].$matches[1],array($this,'_search_count'),array('all'=>true));
                $data  = $list['file_count'] ? $list['file_count'] : '0';
                break;
```

This has worked well. 

**If you get the chance, could you please implement this into the existing code of the plugin or make it an option for those using the plugin**
Thank you

**Comment by RandyVogel** [comment]
I'll second this request -- 0 is a pretty common result!
